### ISSUE TITLE
admin_ssh_key Error during terraform plan

### ISSUE THREAD

**Issue by Ston9** [claranet/terraform-azurerm-linux-vm#1]
**Explanation**

I found an issue related to the SSH key using the last `v.4.1.0` tag (it may occure with the other)

```
Error: Error "admin_ssh_key.0.public_key" is not a complete SSH2 Public Key

  on .terraform/modules/vm/r-vm.tf line 1, in resource "azurerm_linux_virtual_machine" "vm":
   1: resource "azurerm_linux_virtual_machine" "vm" {
```

I tried to use a SSH2 format, but this was not really the issue.
Then, I found this issue on Microsoft Docs GitHub : https://github.com/MicrosoftDocs/azure-docs/issues/51106

**Workaround**

Adding this `file()` cast on the SSH key file on the dynamic bloc fix the issue : 

```
 dynamic "admin_ssh_key" {
    for_each = var.ssh_public_key != null ? ["fake"] : []
    content {
      public_key = file(var.ssh_public_key)
      username   = var.admin_username
    }
  }
```

**Comment by Shr3ps** [comment]
Hello,

`var.ssh_public_key` is the SSH public key like the description stands in README, not a file path, so it seems your issue is only about how to use the module.
